[functions]
directory = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = """
    default-src 'self';
    script-src 'self' https://apis.google.com https://cdn.jsdelivr.net https://cdn.jsdelivr.net/npm;
    style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net;
    img-src 'self' data: https://cdn.jsdelivr.net https://oaidalleapiprodscus.blob.core.windows.net;
    font-src 'self' https://fonts.gstatic.com;
    connect-src 'self' https://api.openai.com https://generativelanguage.googleapis.com https://gemini.googleapis.com;
    frame-ancestors 'none';
    object-src 'none';
    base-uri 'self';
    form-action 'self';
  """.trim()
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
